import type { Species } from './types';

/** English family names and coarse field groups (what a birder would call "what kind of bird is it"). */
export const FAMILY: Record<string, { en: string; group: string }> = {
  // ---- birds ----
  Accipitridae: { en: 'Hawks, eagles & kites', group: 'raptors' },
  Falconidae: { en: 'Falcons', group: 'raptors' },
  Strigidae: { en: 'Owls', group: 'owls' },
  Caprimulgidae: { en: 'Nightjars', group: 'owls' },
  Ardeidae: { en: 'Herons & egrets', group: 'herons' },
  Ciconiidae: { en: 'Storks', group: 'herons' },
  Threskiornithidae: { en: 'Ibises & spoonbills', group: 'herons' },
  Scopidae: { en: 'Hamerkop', group: 'herons' },
  Anatidae: { en: 'Ducks & geese', group: 'waterfowl' },
  Podicipedidae: { en: 'Grebes', group: 'waterfowl' },
  Phalacrocoracidae: { en: 'Cormorants', group: 'waterfowl' },
  Anhingidae: { en: 'Darters', group: 'waterfowl' },
  Charadriidae: { en: 'Plovers & lapwings', group: 'waders' },
  Burhinidae: { en: 'Thick-knees', group: 'waders' },
  Glareolidae: { en: 'Coursers & pratincoles', group: 'waders' },
  Jacanidae: { en: 'Jacanas', group: 'waders' },
  Rostratulidae: { en: 'Painted-snipes', group: 'waders' },
  Rallidae: { en: 'Rails & crakes', group: 'waders' },
  Phasianidae: { en: 'Francolins & spurfowl', group: 'gamebirds' },
  Numididae: { en: 'Guineafowl', group: 'gamebirds' },
  Turnicidae: { en: 'Buttonquails', group: 'gamebirds' },
  Otididae: { en: 'Bustards & korhaans', group: 'gamebirds' },
  Columbidae: { en: 'Pigeons & doves', group: 'doves' },
  Cuculidae: { en: 'Cuckoos & coucals', group: 'cuckoos' },
  Musophagidae: { en: 'Turacos & go-away-birds', group: 'cuckoos' },
  Psittacidae: { en: 'Parrots', group: 'cuckoos' },
  Coliidae: { en: 'Mousebirds', group: 'cuckoos' },
  Apodidae: { en: 'Swifts', group: 'swifts' },
  Hirundinidae: { en: 'Swallows & martins', group: 'swifts' },
  Alcedinidae: { en: 'Kingfishers', group: 'kingfishers' },
  Meropidae: { en: 'Bee-eaters', group: 'kingfishers' },
  Coraciidae: { en: 'Rollers', group: 'kingfishers' },
  Upupidae: { en: 'Hoopoes', group: 'kingfishers' },
  Phoeniculidae: { en: 'Wood hoopoes & scimitarbills', group: 'kingfishers' },
  Bucerotidae: { en: 'Hornbills', group: 'hornbills' },
  Bucorvidae: { en: 'Ground hornbills', group: 'hornbills' },
  Picidae: { en: 'Woodpeckers', group: 'woodpeckers' },
  Lybiidae: { en: 'African barbets', group: 'woodpeckers' },
  Indicatoridae: { en: 'Honeyguides', group: 'woodpeckers' },
  Laniidae: { en: 'Shrikes', group: 'shrikes' },
  Malaconotidae: { en: 'Bushshrikes & tchagras', group: 'shrikes' },
  Vangidae: { en: 'Helmetshrikes', group: 'shrikes' },
  Platysteiridae: { en: 'Batises & wattle-eyes', group: 'shrikes' },
  Eurocephalidae: { en: 'White-crowned shrikes', group: 'shrikes' },
  Campephagidae: { en: 'Cuckooshrikes', group: 'shrikes' },
  Dicruridae: { en: 'Drongos', group: 'shrikes' },
  Oriolidae: { en: 'Orioles', group: 'shrikes' },
  Monarchidae: { en: 'Paradise flycatchers', group: 'shrikes' },
  Corvidae: { en: 'Crows', group: 'shrikes' },
  Turdidae: { en: 'Thrushes', group: 'thrushes' },
  Muscicapidae: { en: 'Chats, robins & flycatchers', group: 'thrushes' },
  Cisticolidae: { en: 'Cisticolas, prinias & apalises', group: 'warblers' },
  Locustellidae: { en: 'Grassbirds & allies', group: 'warblers' },
  Phylloscopidae: { en: 'Leaf warblers', group: 'warblers' },
  Macrosphenidae: { en: 'Crombecs & allies', group: 'warblers' },
  Paridae: { en: 'Tits', group: 'warblers' },
  Remizidae: { en: 'Penduline tits', group: 'warblers' },
  Zosteropidae: { en: 'White-eyes', group: 'warblers' },
  Leiothrichidae: { en: 'Babblers', group: 'warblers' },
  Sturnidae: { en: 'Starlings', group: 'starlings' },
  Buphagidae: { en: 'Oxpeckers', group: 'starlings' },
  Pycnonotidae: { en: 'Bulbuls & greenbuls', group: 'starlings' },
  Nectariniidae: { en: 'Sunbirds', group: 'sunbirds' },
  Passeridae: { en: 'Sparrows', group: 'seedeaters' },
  Ploceidae: { en: 'Weavers & queleas', group: 'seedeaters' },
  Estrildidae: { en: 'Waxbills & firefinches', group: 'seedeaters' },
  Viduidae: { en: 'Whydahs & indigobirds', group: 'seedeaters' },
  Fringillidae: { en: 'Canaries & finches', group: 'seedeaters' },
  Emberizidae: { en: 'Buntings', group: 'seedeaters' },
  Motacillidae: { en: 'Wagtails, pipits & longclaws', group: 'pipits' },
  // ---- mammals ----
  Bovidae: { en: 'Antelopes & buffalo', group: 'antelopes' },
  Canidae: { en: 'Dogs & jackals', group: 'carnivores' },
  Felidae: { en: 'Cats', group: 'carnivores' },
  Hyaenidae: { en: 'Hyenas & aardwolf', group: 'carnivores' },
  Herpestidae: { en: 'Mongooses', group: 'small-carnivores' },
  Viverridae: { en: 'Civets & genets', group: 'small-carnivores' },
  Mustelidae: { en: 'Otters & honey badger', group: 'small-carnivores' },
  Cercopithecidae: { en: 'Monkeys & baboons', group: 'primates' },
  Galagidae: { en: 'Galagos (bushbabies)', group: 'primates' },
  Elephantidae: { en: 'Elephants', group: 'megaherbivores' },
  Rhinocerotidae: { en: 'Rhinos', group: 'megaherbivores' },
  Hippopotamidae: { en: 'Hippos', group: 'megaherbivores' },
  Giraffidae: { en: 'Giraffes', group: 'megaherbivores' },
  Equidae: { en: 'Zebras', group: 'megaherbivores' },
  Suidae: { en: 'Pigs', group: 'megaherbivores' },
  Sciuridae: { en: 'Squirrels', group: 'small-mammals' },
  Leporidae: { en: 'Hares', group: 'small-mammals' },
  Hystricidae: { en: 'Porcupines', group: 'small-mammals' },
  Thryonomyidae: { en: 'Cane rats', group: 'small-mammals' },
  Procaviidae: { en: 'Hyraxes', group: 'small-mammals' },
  Orycteropodidae: { en: 'Aardvark', group: 'small-mammals' },
  Manidae: { en: 'Pangolins', group: 'small-mammals' },
  Pteropodidae: { en: 'Fruit bats', group: 'bats' },
  Emballonuridae: { en: 'Sheath-tailed bats', group: 'bats' },
};

/** Genus-level overrides where a family mixes very different-looking birds. */
const GENUS_GROUP: Record<string, string> = {
  Gyps: 'vultures', Necrosyrtes: 'vultures', Torgos: 'vultures', Trigonoceps: 'vultures',
};

export const BIRD_GROUPS: [string, string][] = [
  ['raptors', 'Raptors: eagles, hawks, kites, falcons'],
  ['vultures', 'Vultures'],
  ['owls', 'Owls & nightjars'],
  ['herons', 'Herons, storks, ibises, hamerkop'],
  ['waterfowl', 'Ducks, geese, grebes, cormorants'],
  ['waders', 'Lapwings, plovers, thick-knees, crakes'],
  ['gamebirds', 'Francolins, guineafowl, bustards'],
  ['doves', 'Pigeons & doves'],
  ['cuckoos', 'Cuckoos, coucals, turacos, parrots, mousebirds'],
  ['swifts', 'Swifts & swallows'],
  ['kingfishers', 'Kingfishers, bee-eaters, rollers, hoopoes'],
  ['hornbills', 'Hornbills'],
  ['woodpeckers', 'Woodpeckers, barbets, honeyguides'],
  ['shrikes', 'Shrikes, bushshrikes, drongos, orioles, crows'],
  ['thrushes', 'Thrushes, chats, robins, flycatchers'],
  ['warblers', 'Warblers, cisticolas, tits, babblers'],
  ['starlings', 'Starlings, oxpeckers, bulbuls'],
  ['sunbirds', 'Sunbirds'],
  ['seedeaters', 'Sparrows, weavers, waxbills, canaries'],
  ['pipits', 'Pipits, wagtails, longclaws'],
];

export const groupOf = (s: Species): string | null => {
  const genus = s.sci.split(' ')[0];
  if (GENUS_GROUP[genus]) return GENUS_GROUP[genus];
  return (s.family && FAMILY[s.family]?.group) || null;
};
export const familyEn = (s: Species): string => (s.family && FAMILY[s.family]?.en) || s.family || '';
export const groupLabel = (g: string) => BIRD_GROUPS.find(([k]) => k === g)?.[1] || g;
